baseURL = 'https://TreeFanx.github.io/'
languageCode = "zh-cn"
title = "TreeFan"
theme = "PaperMod"

[params]
  author = "TreeFan"
  description = "TreeFan 的个人博客"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"

  [params.homeInfoParams]
    Title = "Hi, 我是 TreeFan 👋"
    Content = "欢迎来到我的博客，这里记录我的思考与分享。"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/TreeFanx"
